<?php

return [
    'stays.index' => [
        'name' => '住宿列表',
        'module_group' => 'stays',
        'web_route_name' => 'site.stays.index',
        'web_route_params' => [],
        'uniapp_path' => null,
        'description' => '前台住宿浏览首页',
    ],
    'stays.show' => [
        'name' => '房源详情',
        'module_group' => 'stays',
        'web_route_name' => 'site.stays.show',
        'web_route_params' => [],
        'uniapp_path' => null,
        'description' => '单房源详情（动态 {listing} 由视图生成）',
    ],
    'bookings.confirmation' => [
        'name' => '预订确认',
        'module_group' => 'bookings',
        'web_route_name' => 'site.bookings.confirmation',
        'web_route_params' => [],
        'uniapp_path' => null,
        'description' => null,
    ],
    'bookings.show' => [
        'name' => '订单详情',
        'module_group' => 'bookings',
        'web_route_name' => 'site.bookings.show',
        'web_route_params' => [],
        'uniapp_path' => null,
        'description' => null,
    ],
    'account.bookings' => [
        'name' => '我的订单',
        'module_group' => 'account',
        'web_route_name' => 'site.me.bookings',
        'web_route_params' => [],
        'uniapp_path' => null,
        'description' => null,
    ],
    'docs.stored-urls-intro' => [
        'name' => 'URL 入库说明',
        'module_group' => 'docs',
        'web_route_name' => 'docs.stored-urls-intro',
        'web_route_params' => [],
        'uniapp_path' => null,
        'description' => null,
    ],
    'landlord.portal-login' => [
        'name' => '房东门户登录',
        'module_group' => 'landlord',
        'web_route_name' => null,
        'web_route_params' => [],
        'uniapp_path' => null,
        'description' => '外链 /landlord-portal/login',
    ],
    'uniapp.index' => [
        'name' => 'UniApp 首页',
        'module_group' => 'uniapp',
        'web_route_name' => null,
        'web_route_params' => [],
        'uniapp_path' => '/pages/index/index',
        'description' => null,
    ],
    'uniapp.login' => [
        'name' => 'UniApp 登录',
        'module_group' => 'uniapp',
        'web_route_name' => null,
        'web_route_params' => [],
        'uniapp_path' => '/pages/login/index',
        'description' => null,
    ],
    'uniapp.profile' => [
        'name' => 'UniApp 个人资料',
        'module_group' => 'uniapp',
        'web_route_name' => null,
        'web_route_params' => [],
        'uniapp_path' => '/pages/user/profile',
        'description' => null,
    ],
];
